version: '3'

services:

  https-portal:
    image: steveltn/https-portal:1
    container_name: mathnetPortal
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: '${DOMAIN}'
      STAGE: ${STAGE}
    volumes:
      - ./docker/portal/certs:/var/lib/https-portal
      - ./docker/portal/nginx/default.conf.erb:/var/lib/nginx-conf/default.conf.erb:ro
      - ./docker/portal/nginx/default.ssl.conf.erb:/var/lib/nginx-conf/default.ssl.conf.erb:ro
      - ./DollorBox/static:/var/www/html/static
      - ./DollorBox/media:/var/www/html/media
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: mathnetApp
    ports:
      - 8000:8000 # debug用
    volumes:
      - ./DollorBox:/var/www/html
    depends_on:
      - db
    command: # dbの起動が終わるまで待つ
      - "bash"
      - "-c"
      - "while !</dev/tcp/db/5432; do sleep 1; done; bash /docker-init/container-init.sh"

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
      args:
        - DB_LANG=en_US
    container_name: mathnetDB
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: ${TZ}
    ports:
      - 5432:5432
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/db/data:/var/lib/postgresql/data # 初期起動では落ちる？原因不明
      - ./docker/db/backup:/var/backup/
    